install:
	npm install rx @cycle/core @cycle/dom @cycle/http babel-loader@5.3.3 webpack webpack-dev-server
serve:
	node_modules/webpack-dev-server/bin/webpack-dev-server.js --watch --progress --colors
watch:
	node_modules/webpack/bin/webpack.js --watch
